require("amkia.packer")
require("amkia.set")
require("amkia.remap")

--vim.o.background = "dark"
--vim.cmd([[colorscheme gruvbox]])
--vim.cmd([[colorscheme gruvbox-material]])
--vim.cmd([[colorscheme everforest]])
--vim.cmd([[colorscheme kanagawa]])
vim.cmd([[colorscheme bogster]])
--vim.cmd([[colorscheme srcery]])
--vim.cmd([[colorscheme papercolor]])
--vim.cmd([[colorscheme deus]])
--vim.cmd([[colorscheme luna]])
--vim.cmd([[colorscheme seattle]])
--vim.cmd([[colorscheme bubblegum-256-dark]])
